AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*
    - vendor/**/.*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/AlignHash:
  Enabled: false
