default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", nil) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", nil) %>

development:
  <<: *default
  database: my_sales_funnel_development

test:
  <<: *default
  database: my_sales_funnel_test

production:
  <<: *default
  database: my_sales_funnel_production
  username: my_sales_funnel
  password: <%= ENV['MY_SALES_FUNNEL_DATABASE_PASSWORD'] %>
